"""
reporter.py — Report Generator

Produces both a CSV and a structured PDF from a completed validation run.
No external services. Uses:
  - Python stdlib `csv`  for CSV
  - reportlab            for PDF

PDF sections:
  1. Header (title, timestamp, disclaimer)
  2. Summary (counts, overall compliance score, disqualification status)
  3. Detailed results table
  4. Risk flags (vague + conditional items surfaced separately)
  5. Final recommendation
  6. Legal disclaimer footer
"""

import csv
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate, Frame, HRFlowable, PageTemplate,
    Paragraph, Spacer, Table, TableStyle,
)

# ── Colour palette (matches the dark UI in spirit, but PDF-safe) ──────────────
C_DARK   = colors.HexColor("#1a1d27")
C_ACCENT = colors.HexColor("#6c63ff")
C_MET    = colors.HexColor("#22c55e")
C_VAGUE  = colors.HexColor("#f59e0b")
C_PART   = colors.HexColor("#3b82f6")
C_NOTMET = colors.HexColor("#ef4444")
C_DISQ   = colors.HexColor("#ef4444")
C_HIGH   = colors.HexColor("#f97316")
C_MUTED  = colors.HexColor("#7c82a0")
C_ROW1   = colors.HexColor("#f8f8fc")
C_ROW2   = colors.white
C_HEAD   = colors.HexColor("#eeeef8")

VERDICT_COLOR = {
    "MET":           C_MET,
    "MET_BUT_VAGUE": C_VAGUE,
    "PARTIAL":       C_PART,
    "NOT_MET":       C_NOTMET,
}
VERDICT_LABEL = {
    "MET":           "Met",
    "MET_BUT_VAGUE": "Met (Vague)",
    "PARTIAL":       "Partial",
    "NOT_MET":       "Not Met",
}
RISK_COLOR = {
    "DISQUALIFYING": C_DISQ,
    "HIGH_RISK":     C_HIGH,
    "STANDARD":      C_MUTED,
}


# ─────────────────────────────────────────────────────────────────────────────
# Shared helper
# ─────────────────────────────────────────────────────────────────────────────

def _overall_compliance_score(results: list[dict]) -> int:
    """
    Weighted compliance score:
      MET           → 1.00
      MET_BUT_VAGUE → 0.75  (topic covered but commitment is weak)
      PARTIAL       → 0.50
      NOT_MET       → 0.00
    """
    if not results:
        return 0
    weights = {"MET": 1.0, "MET_BUT_VAGUE": 0.75, "PARTIAL": 0.50, "NOT_MET": 0.0}
    total = sum(weights.get(r["verdict"], 0) for r in results)
    return int((total / len(results)) * 100)


# ─────────────────────────────────────────────────────────────────────────────
# CSV Export
# ─────────────────────────────────────────────────────────────────────────────

def generate_csv(results: list[dict], summary: dict, overall_status: str) -> bytes:
    """
    Returns raw CSV bytes ready to stream to the client.
    Columns: ID, Requirement, Category, Risk Level, Verdict,
             Semantic Match %, Compliance Score %, Vague, Hedge Phrases,
             Has Conditions, Conditions, Match Excerpt
    """
    output = io.StringIO()
    writer = csv.writer(output)

    # ── Metadata header rows ──
    writer.writerow(["Tender Compliance Report"])
    writer.writerow(["Generated", datetime.now().strftime("%Y-%m-%d %H:%M")])
    writer.writerow(["Overall Status", overall_status])
    writer.writerow(["Overall Compliance Score", f"{_overall_compliance_score(results)}%"])
    writer.writerow([])

    # ── Summary block ──
    writer.writerow(["Summary"])
    for k, v in summary.items():
        writer.writerow([k.replace("_", " ").title(), v])
    writer.writerow([])

    # ── Column headers ──
    writer.writerow([
        "ID", "Requirement", "Category", "Risk Level", "Verdict",
        "Semantic Match %", "Compliance Score %",
        "Vague?", "Hedge Phrases",
        "Has Conditions?", "Conditions",
        "Match Excerpt",
    ])

    # ── Data rows ──
    for r in results:
        writer.writerow([
            r.get("id", ""),
            r.get("requirement", ""),
            r.get("category", ""),
            r.get("risk_level", "STANDARD"),
            VERDICT_LABEL.get(r.get("verdict", ""), r.get("verdict", "")),
            r.get("semantic_similarity", ""),
            r.get("compliance_score", ""),
            "Yes" if r.get("is_vague") else "No",
            "; ".join(r.get("hedge_phrases_found", [])),
            "Yes" if r.get("has_conditions") else "No",
            "; ".join(r.get("conditions_found", [])),
            r.get("best_match_excerpt", ""),
        ])

    writer.writerow([])
    writer.writerow(["DISCLAIMER: This report is generated by an automated AI tool for"
                     " informational purposes only. It does not constitute legal or"
                     " procurement advice. Final decisions remain the responsibility"
                     " of the procuring organisation."])

    return output.getvalue().encode("utf-8-sig")  # BOM for Excel compatibility


# ─────────────────────────────────────────────────────────────────────────────
# PDF Export
# ─────────────────────────────────────────────────────────────────────────────

def generate_pdf(
    results: list[dict],
    summary: dict,
    overall_status: str,
    disqualifying_failures: list[dict],
) -> bytes:
    """
    Returns raw PDF bytes ready to stream to the client.
    """
    buffer = io.BytesIO()

    # ── Page layout ──────────────────────────────────────────────────────────
    doc = BaseDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
    )

    page_w, page_h = A4
    usable_w = page_w - 4 * cm

    def _header_footer(canvas, doc):
        canvas.saveState()
        # Header bar
        canvas.setFillColor(C_ACCENT)
        canvas.rect(2 * cm, page_h - 1.8 * cm, usable_w, 0.35 * cm, fill=1, stroke=0)
        # Footer
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(C_MUTED)
        canvas.drawString(2 * cm, 1.3 * cm, "Tender Compliance Validator — Automated Report")
        canvas.drawRightString(
            page_w - 2 * cm, 1.3 * cm,
            f"Page {doc.page}  |  Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        )
        canvas.restoreState()

    frame = Frame(doc.leftMargin, doc.bottomMargin,
                  usable_w, page_h - 4.5 * cm, id="main")
    doc.addPageTemplates([PageTemplate(id="base", frames=[frame], onPage=_header_footer)])

    # ── Styles ────────────────────────────────────────────────────────────────
    base = getSampleStyleSheet()

    sTitle = ParagraphStyle("sTitle", parent=base["Title"],
                            fontSize=22, textColor=C_ACCENT,
                            spaceAfter=4, alignment=TA_LEFT, fontName="Helvetica-Bold")
    sSub   = ParagraphStyle("sSub",   parent=base["Normal"],
                            fontSize=9, textColor=C_MUTED,
                            spaceAfter=16, alignment=TA_LEFT)
    sSec   = ParagraphStyle("sSec",   parent=base["Heading2"],
                            fontSize=12, textColor=C_DARK,
                            spaceBefore=18, spaceAfter=8, fontName="Helvetica-Bold")
    sBody  = ParagraphStyle("sBody",  parent=base["Normal"],
                            fontSize=8.5, textColor=colors.HexColor("#22263a"),
                            leading=13)
    sSmall = ParagraphStyle("sSmall", parent=base["Normal"],
                            fontSize=7.5, textColor=C_MUTED, leading=11)
    sDisq  = ParagraphStyle("sDisq",  parent=base["Normal"],
                            fontSize=9, textColor=C_DISQ,
                            leading=14, fontName="Helvetica-Bold")
    sDisqBody = ParagraphStyle("sDisqBody", parent=base["Normal"],
                               fontSize=8.5, textColor=colors.HexColor("#dc2626"), leading=13)
    sRec   = ParagraphStyle("sRec",   parent=base["Normal"],
                            fontSize=9, textColor=colors.HexColor("#1e293b"),
                            leading=14, fontName="Helvetica-Bold")
    sDisc  = ParagraphStyle("sDisc",  parent=base["Normal"],
                            fontSize=7, textColor=C_MUTED, leading=10)

    story = []

    # ─── Section 1: Title ────────────────────────────────────────────────────
    story.append(Paragraph("Tender Compliance Report", sTitle))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}  |  "
        f"Tool: Tender Compliance Validator (Free Edition)", sSub
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=C_ACCENT, spaceAfter=14))

    # ─── Section 2: Summary ──────────────────────────────────────────────────
    story.append(Paragraph("1. Summary", sSec))

    score = _overall_compliance_score(results)
    status_color = C_DISQ if overall_status == "DISQUALIFIED" else C_MET
    status_label = "❌  DISQUALIFIED" if overall_status == "DISQUALIFIED" else "✅  PASSED"

    sum_data = [
        ["Metric", "Value"],
        ["Total Requirements",  str(summary.get("total", 0))],
        ["Met",                 str(summary.get("met", 0))],
        ["Met (Vague)",         str(summary.get("met_but_vague", 0))],
        ["Partial",             str(summary.get("partial", 0))],
        ["Not Met",             str(summary.get("not_met", 0))],
        ["Conditional Matches", str(summary.get("with_conditions", 0))],
        ["Overall Compliance Score", f"{score}%"],
        ["Vendor Status",       status_label],
    ]

    sum_table = Table(sum_data, colWidths=[usable_w * 0.6, usable_w * 0.4])
    sum_style = TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), C_ACCENT),
        ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
        ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, 0), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_ROW1, C_ROW2]),
        ("FONTSIZE",     (0, 1), (-1, -1), 8.5),
        ("TEXTCOLOR",    (1, -1), (1, -1), status_color),
        ("FONTNAME",     (1, -1), (1, -1), "Helvetica-Bold"),
        ("TEXTCOLOR",    (1, -2), (1, -2),
         colors.HexColor("#15803d") if score >= 70 else (C_VAGUE if score >= 50 else C_NOTMET)),
        ("FONTNAME",     (1, -2), (1, -2), "Helvetica-Bold"),
        ("ALIGN",        (1, 0), (1, -1), "CENTER"),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ("ROWHEIGHT",   (0, 0), (-1, -1), 18),
        ("GRID",         (0, 0), (-1, -1), 0.4, colors.HexColor("#d1d5db")),
        ("LEFTPADDING",  (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ])
    sum_table.setStyle(sum_style)
    story.append(sum_table)

    # Disqualification alert box
    if overall_status == "DISQUALIFIED":
        story.append(Spacer(1, 12))
        story.append(Paragraph("⛔  DISQUALIFICATION ALERT", sDisq))
        for f in disqualifying_failures:
            story.append(Paragraph(
                f"• [Req #{f['id']}] {f['requirement']}  →  {VERDICT_LABEL.get(f['verdict'], f['verdict'])}",
                sDisqBody
            ))

    # ─── Section 3: Detailed Results Table ───────────────────────────────────
    story.append(Paragraph("2. Detailed Results", sSec))

    col_w = [
        usable_w * 0.04,  # #
        usable_w * 0.31,  # Requirement
        usable_w * 0.13,  # Category
        usable_w * 0.10,  # Risk
        usable_w * 0.12,  # Verdict
        usable_w * 0.09,  # Semantic %
        usable_w * 0.09,  # Compliance %
        usable_w * 0.12,  # Evidence
    ]

    tbl_data = [[
        Paragraph("#", sSmall),
        Paragraph("Requirement", sSmall),
        Paragraph("Category", sSmall),
        Paragraph("Risk", sSmall),
        Paragraph("Verdict", sSmall),
        Paragraph("Semantic\nMatch", sSmall),
        Paragraph("Compliance\nScore", sSmall),
        Paragraph("Evidence", sSmall),
    ]]

    row_colors = []
    for i, r in enumerate(results):
        v = r.get("verdict", "NOT_MET")
        vc = VERDICT_COLOR.get(v, C_MUTED)
        rc = RISK_COLOR.get(r.get("risk_level", "STANDARD"), C_MUTED)

        excerpt = r.get("best_match_excerpt", "") or "—"
        if len(excerpt) > 90:
            excerpt = excerpt[:87] + "…"

        sem  = r.get("semantic_similarity", 0)
        comp = r.get("compliance_score", 0)

        tbl_data.append([
            Paragraph(str(r.get("id", "")), sSmall),
            Paragraph(r.get("requirement", ""), sSmall),
            Paragraph(r.get("category", "General"), sSmall),
            Paragraph(r.get("risk_level", "STANDARD").replace("_", " ").title(), sSmall),
            Paragraph(f'<font color="{vc.hexval()}">{VERDICT_LABEL.get(v, v)}</font>', sSmall),
            Paragraph(f"{sem}%", sSmall),
            Paragraph(f"{comp}%", sSmall),
            Paragraph(f'<i>{excerpt}</i>', sSmall),
        ])
        row_colors.append(C_ROW1 if i % 2 == 0 else C_ROW2)

    results_table = Table(tbl_data, colWidths=col_w, repeatRows=1)
    rt_style = [
        ("BACKGROUND",   (0, 0), (-1, 0), C_DARK),
        ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
        ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, 0), 7.5),
        ("ALIGN",        (0, 0), (-1, 0), "CENTER"),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("GRID",         (0, 0), (-1, -1), 0.3, colors.HexColor("#d1d5db")),
        ("LEFTPADDING",  (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
    ]
    for i, bg in enumerate(row_colors, start=1):
        rt_style.append(("BACKGROUND", (0, i), (-1, i), bg))
    results_table.setStyle(TableStyle(rt_style))
    story.append(results_table)

    # ─── Section 4: Risk Flags ───────────────────────────────────────────────
    story.append(Paragraph("3. Risk Flags", sSec))

    vague_items = [r for r in results if r.get("is_vague")]
    cond_items  = [r for r in results if r.get("has_conditions")]

    if not vague_items and not cond_items:
        story.append(Paragraph("No risk flags identified.", sBody))
    else:
        if vague_items:
            story.append(Paragraph("Vague Commitments Detected", sRec))
            for r in vague_items:
                phrases = ", ".join(f'"{p}"' for p in r.get("hedge_phrases_found", []))
                story.append(Paragraph(
                    f"• Req #{r['id']}: {r['requirement'][:80]}…  →  Hedge phrases: {phrases}",
                    sSmall
                ))
            story.append(Spacer(1, 6))

        if cond_items:
            story.append(Paragraph("Conditional Clauses Detected", sRec))
            for r in cond_items:
                clauses = "; ".join(f'"{c}"' for c in r.get("conditions_found", []))
                story.append(Paragraph(
                    f"• Req #{r['id']}: {r['requirement'][:80]}…  →  Conditions: {clauses}",
                    sSmall
                ))

    # ─── Section 5: Final Recommendation ────────────────────────────────────
    story.append(Paragraph("4. Final Recommendation", sSec))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=8))

    if overall_status == "DISQUALIFIED":
        rec_text = (
            f"<b>Vendor is NOT recommended.</b> The proposal failed {len(disqualifying_failures)} "
            f"disqualifying requirement(s) — which are mandatory legal, licensing, or certification "
            f"obligations. Failure to satisfy these is grounds for immediate bid rejection regardless "
            f"of overall compliance score ({score}%)."
        )
        rec_color = C_DISQ
    elif score >= 80:
        rec_text = (
            f"<b>Vendor is recommended for further review.</b> The proposal demonstrates strong "
            f"overall compliance ({score}%). Minor gaps identified should be clarified before contract award."
        )
        rec_color = C_MET
    elif score >= 50:
        rec_text = (
            f"<b>Vendor requires clarification before recommendation.</b> Overall compliance score "
            f"is {score}%, with notable partial matches and/or vague commitments. Outstanding items "
            f"must be addressed in writing before contract award."
        )
        rec_color = C_VAGUE
    else:
        rec_text = (
            f"<b>Vendor is not recommended.</b> Overall compliance score is {score}%, indicating "
            f"significant gaps across core requirements. Recommend rejection or re-submission."
        )
        rec_color = C_NOTMET

    rec_style = ParagraphStyle("sRecColored", parent=sBody,
                               textColor=rec_color, fontSize=9, leading=14)
    story.append(Paragraph(rec_text, rec_style))

    # ─── Disclaimer ──────────────────────────────────────────────────────────
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.4, color=C_MUTED, spaceAfter=6))
    story.append(Paragraph(
        "DISCLAIMER: This report is generated by an automated AI tool for informational purposes only. "
        "It does not constitute legal, procurement, or contractual advice. Semantic matching may not "
        "capture all legal nuances. Final evaluation decisions remain the sole responsibility of the "
        "procuring organisation and its qualified personnel.",
        sDisc
    ))

    # ── Build ────────────────────────────────────────────────────────────────
    doc.build(story)
    buffer.seek(0)
    return buffer.read()
