"""
reporter.py - Report Generator

Produces CSV and PDF exports from a completed validation run.
"""

import csv
import io
from datetime import datetime
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

C_DARK = colors.HexColor("#1a1d27")
C_ACCENT = colors.HexColor("#6c63ff")
C_MET = colors.HexColor("#22c55e")
C_WARN = colors.HexColor("#f59e0b")
C_PART = colors.HexColor("#3b82f6")
C_NOTMET = colors.HexColor("#ef4444")
C_MUTED = colors.HexColor("#7c82a0")
C_ROW1 = colors.HexColor("#f8f8fc")
C_ROW2 = colors.white

VERDICT_COLOR = {
    "MET": C_MET,
    "MET_BUT_VAGUE": C_WARN,
    "PARTIAL": C_PART,
    "NOT_MET": C_NOTMET,
}

VERDICT_LABEL = {
    "MET": "Met",
    "MET_BUT_VAGUE": "Met (Vague)",
    "PARTIAL": "Partial",
    "NOT_MET": "Not Met",
}


def _yes_no(value: bool) -> str:
    return "Yes" if value else "No"


def generate_csv(
    results: list[dict],
    summary: dict,
    overall_status: str,
    mode: str,
    overall_score: int,
    critical_failure: dict | None,
    category_breakdown: list[dict],
    top_issues: list[dict],
) -> bytes:
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow(["Tender Compliance Report"])
    writer.writerow(["Generated", datetime.now().strftime("%Y-%m-%d %H:%M")])
    writer.writerow(["Validation Mode", mode.title()])
    writer.writerow(["Overall Status", overall_status])
    writer.writerow(["Overall Compliance Score", f"{overall_score}%"])
    if critical_failure:
        writer.writerow(["Critical Failure", critical_failure["message"]])
    writer.writerow([])

    writer.writerow(["Summary"])
    for key, value in summary.items():
        writer.writerow([key.replace("_", " ").title(), value])
    writer.writerow([])

    writer.writerow(["Category Breakdown"])
    writer.writerow(["Category", "Score %", "Total", "Met", "Partial", "Not Met", "Weak Commitments"])
    for item in category_breakdown:
        writer.writerow([
            item["category"],
            item["score"],
            item["total"],
            item["met"],
            item["partial"],
            item["not_met"],
            item["weak_commitments"],
        ])
    writer.writerow([])

    writer.writerow(["Top 3 Weakest Areas"])
    writer.writerow(["Priority", "Issue", "Detail", "Severity"])
    for index, issue in enumerate(top_issues, start=1):
        writer.writerow([index, issue["title"], issue["detail"], issue["severity"]])
    writer.writerow([])

    writer.writerow([
        "ID",
        "Requirement",
        "Category",
        "Risk Level",
        "Base Verdict",
        "Final Verdict",
        "Semantic Match %",
        "Compliance Score %",
        "Explicit Commitment?",
        "Commitment Phrases",
        "Vague?",
        "Hedge Phrases",
        "Has Conditions?",
        "Conditions",
        "Why This Verdict?",
        "Why This Matters",
        "Match Excerpt",
    ])

    for result in results:
        writer.writerow([
            result.get("id", ""),
            result.get("requirement", ""),
            result.get("category", ""),
            result.get("risk_level", "STANDARD"),
            VERDICT_LABEL.get(result.get("base_verdict", ""), result.get("base_verdict", "")),
            VERDICT_LABEL.get(result.get("verdict", ""), result.get("verdict", "")),
            result.get("semantic_similarity", ""),
            result.get("compliance_score", ""),
            _yes_no(result.get("explicit_commitment_found", False)),
            "; ".join(result.get("commitment_phrases_found", [])),
            _yes_no(result.get("is_vague", False)),
            "; ".join(result.get("hedge_phrases_found", [])),
            _yes_no(result.get("has_conditions", False)),
            "; ".join(result.get("conditions_found", [])),
            " | ".join(result.get("verdict_reasons", [])),
            result.get("why_this_matters", ""),
            result.get("best_match_excerpt", ""),
        ])

    writer.writerow([])
    writer.writerow([
        "DISCLAIMER",
        "This report is generated by an automated AI tool for informational purposes only. "
        "It does not constitute legal or procurement advice.",
    ])

    return output.getvalue().encode("utf-8-sig")


def generate_pdf(
    results: list[dict],
    summary: dict,
    overall_status: str,
    disqualifying_failures: list[dict],
    mode: str,
    overall_score: int,
    critical_failure: dict | None,
    category_breakdown: list[dict],
    top_issues: list[dict],
) -> bytes:
    buffer = io.BytesIO()
    doc = BaseDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=1.7 * cm,
        rightMargin=1.7 * cm,
        topMargin=2.3 * cm,
        bottomMargin=1.8 * cm,
    )

    page_w, page_h = A4
    usable_w = page_w - doc.leftMargin - doc.rightMargin

    def _header_footer(canvas, document):
        canvas.saveState()
        canvas.setFillColor(C_ACCENT)
        canvas.rect(doc.leftMargin, page_h - 1.4 * cm, usable_w, 0.25 * cm, fill=1, stroke=0)
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(C_MUTED)
        canvas.drawString(doc.leftMargin, 1.2 * cm, "Tender Compliance Validator - Automated Report")
        canvas.drawRightString(
            page_w - doc.rightMargin,
            1.2 * cm,
            f"Page {document.page} | Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        )
        canvas.restoreState()

    frame = Frame(doc.leftMargin, doc.bottomMargin, usable_w, page_h - 4.1 * cm, id="main")
    doc.addPageTemplates([PageTemplate(id="base", frames=[frame], onPage=_header_footer)])

    base = getSampleStyleSheet()
    s_title = ParagraphStyle(
        "title",
        parent=base["Title"],
        fontSize=20,
        textColor=C_ACCENT,
        alignment=TA_LEFT,
        spaceAfter=4,
    )
    s_sub = ParagraphStyle(
        "sub",
        parent=base["Normal"],
        fontSize=9,
        textColor=C_MUTED,
        leading=12,
        spaceAfter=12,
    )
    s_section = ParagraphStyle(
        "section",
        parent=base["Heading2"],
        fontSize=12,
        textColor=C_DARK,
        spaceBefore=16,
        spaceAfter=8,
    )
    s_body = ParagraphStyle(
        "body",
        parent=base["Normal"],
        fontSize=8.5,
        textColor=colors.HexColor("#22263a"),
        leading=12,
    )
    s_small = ParagraphStyle(
        "small",
        parent=base["Normal"],
        fontSize=7.5,
        textColor=colors.HexColor("#334155"),
        leading=10,
    )
    s_muted = ParagraphStyle(
        "muted",
        parent=base["Normal"],
        fontSize=7.2,
        textColor=C_MUTED,
        leading=10,
    )
    s_alert = ParagraphStyle(
        "alert",
        parent=base["Normal"],
        fontSize=9,
        textColor=C_NOTMET,
        leading=13,
    )

    story = [
        Paragraph("Tender Compliance Report", s_title),
        Paragraph(
            f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')} | "
            f"Validation Mode: {escape(mode.title())} | Overall Score: {overall_score}%",
            s_sub,
        ),
        HRFlowable(width="100%", thickness=1, color=C_ACCENT, spaceAfter=10),
    ]

    story.append(Paragraph("1. Executive Summary", s_section))
    summary_rows = [
        ["Metric", "Value"],
        ["Vendor Status", overall_status],
        ["Validation Mode", mode.title()],
        ["Overall Compliance Score", f"{overall_score}%"],
        ["Total Requirements", str(summary.get("total", 0))],
        ["Met", str(summary.get("met", 0))],
        ["Partial", str(summary.get("partial", 0))],
        ["Not Met", str(summary.get("not_met", 0))],
        ["Vague Matches", str(summary.get("met_but_vague", 0))],
        ["Conditional Matches", str(summary.get("with_conditions", 0))],
    ]
    summary_table = Table(summary_rows, colWidths=[usable_w * 0.58, usable_w * 0.42])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), C_ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_ROW1, C_ROW2]),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#d1d5db")),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(summary_table)

    if critical_failure:
        story.append(Spacer(1, 10))
        story.append(Paragraph("CRITICAL FAILURE", s_alert))
        story.append(Paragraph(escape(critical_failure["message"]), s_alert))
        for failure in disqualifying_failures:
            story.append(Paragraph(
                f"- Req #{failure['id']}: {escape(failure['requirement'])} "
                f"({escape(VERDICT_LABEL.get(failure['verdict'], failure['verdict']))})",
                s_small,
            ))

    story.append(Paragraph("2. Category Score Breakdown", s_section))
    category_rows = [["Category", "Score", "Met", "Partial", "Not Met", "Weak"]]
    for item in category_breakdown:
        category_rows.append([
            item["category"],
            f"{item['score']}%",
            str(item["met"]),
            str(item["partial"]),
            str(item["not_met"]),
            str(item["weak_commitments"]),
        ])
    category_table = Table(
        category_rows,
        colWidths=[
            usable_w * 0.34,
            usable_w * 0.12,
            usable_w * 0.12,
            usable_w * 0.12,
            usable_w * 0.12,
            usable_w * 0.12,
        ],
        repeatRows=1,
    )
    category_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), C_DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_ROW1, C_ROW2]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#d1d5db")),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(category_table)

    story.append(Paragraph("3. Top 3 Weakest Areas", s_section))
    if top_issues:
        for index, issue in enumerate(top_issues, start=1):
            story.append(Paragraph(
                f"<b>{index}. {escape(issue['title'])}</b> - {escape(issue['detail'])}",
                s_body,
            ))
    else:
        story.append(Paragraph("No material weaknesses identified.", s_body))

    story.append(Paragraph("4. Detailed Results", s_section))
    result_rows = [[
        "#",
        "Requirement",
        "Category",
        "Verdict",
        "Semantic",
        "Compliance",
    ]]
    for result in results:
        result_rows.append([
            str(result.get("id", "")),
            Paragraph(escape(result.get("requirement", "")), s_small),
            Paragraph(escape(result.get("category", "General")), s_small),
            Paragraph(
                f'<font color="{VERDICT_COLOR.get(result.get("verdict"), C_NOTMET).hexval()}">'
                f"{escape(VERDICT_LABEL.get(result.get('verdict', ''), result.get('verdict', '')))}</font>",
                s_small,
            ),
            f"{result.get('semantic_similarity', 0)}%",
            f"{result.get('compliance_score', 0)}%",
        ])
    result_table = Table(
        result_rows,
        colWidths=[
            usable_w * 0.05,
            usable_w * 0.41,
            usable_w * 0.18,
            usable_w * 0.14,
            usable_w * 0.10,
            usable_w * 0.12,
        ],
        repeatRows=1,
    )
    result_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), C_DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_ROW1, C_ROW2]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#d1d5db")),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (3, 0), (-1, -1), "CENTER"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(result_table)

    story.append(Paragraph("5. Why This Verdict", s_section))
    for result in results:
        verdict_text = VERDICT_LABEL.get(result.get("verdict", ""), result.get("verdict", ""))
        story.append(Paragraph(
            f"<b>Req #{result.get('id')}</b> - {escape(result.get('requirement', ''))} "
            f"(<font color=\"{VERDICT_COLOR.get(result.get('verdict'), C_NOTMET).hexval()}\">{escape(verdict_text)}</font>)",
            s_body,
        ))
        reasons = result.get("verdict_reasons", [])
        if reasons:
            story.append(Paragraph(
                "<br/>".join(f"- {escape(reason)}" for reason in reasons),
                s_small,
            ))
        story.append(Paragraph(
            f"<b>Why this matters:</b> {escape(result.get('why_this_matters', ''))}",
            s_muted,
        ))
        excerpt = result.get("best_match_excerpt", "")
        if excerpt:
            story.append(Paragraph(
                f"<i>Evidence:</i> {escape(excerpt[:220])}",
                s_muted,
            ))
        story.append(Spacer(1, 6))

    story.append(Paragraph("6. Final Recommendation", s_section))
    if overall_status == "DISQUALIFIED":
        recommendation = (
            f"<b>Vendor is not recommended.</b> {len(disqualifying_failures)} disqualifying "
            "requirement(s) failed, so immediate rejection is recommended regardless of the overall score."
        )
        recommendation_color = C_NOTMET
    elif overall_score >= 80:
        recommendation = (
            "<b>Vendor is recommended for further review.</b> Overall compliance is strong, with only limited gaps "
            "that should be clarified before award."
        )
        recommendation_color = C_MET
    elif overall_score >= 50:
        recommendation = (
            "<b>Vendor needs clarification before recommendation.</b> Partial coverage and qualified language create "
            "material review risk."
        )
        recommendation_color = C_WARN
    else:
        recommendation = (
            "<b>Vendor is not recommended.</b> Significant compliance gaps remain across key requirements."
        )
        recommendation_color = C_NOTMET

    recommendation_style = ParagraphStyle(
        "recommendation",
        parent=s_body,
        textColor=recommendation_color,
        fontSize=9,
        leading=13,
    )
    story.append(Paragraph(recommendation, recommendation_style))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.4, color=C_MUTED, spaceAfter=6))
    story.append(Paragraph(
        "DISCLAIMER: This report is generated by an automated AI tool for informational purposes only. "
        "It does not constitute legal, procurement, or contractual advice. Final evaluation decisions remain "
        "the responsibility of the procuring organisation.",
        s_muted,
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
